// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDYZ1XIomOuWFoCL-9v1YLf96-dw5jdgU',
    appId: '1:896053782358:web:0d9458d20f533c815318f7',
    messagingSenderId: '896053782358',
    projectId: 'routemate-470316',
    authDomain: 'routemate-470316.firebaseapp.com',
    storageBucket: 'routemate-470316.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDYZ1XIomOuWFoCL-9v1YLf96-dw5jdgU',
    appId: '1:896053782358:android:0d9458d20f533c815318f7',
    messagingSenderId: '896053782358',
    projectId: 'routemate-470316',
    storageBucket: 'routemate-470316.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDYZ1XIomOuWFoCL-9v1YLf96-dw5jdgU',
    appId: '1:896053782358:ios:0d9458d20f533c815318f7',
    messagingSenderId: '896053782358',
    projectId: 'routemate-470316',
    storageBucket: 'routemate-470316.firebasestorage.app',
    iosClientId: '896053782358-abcdefghijklmnopqrstuvwxyz123456.apps.googleusercontent.com',
    iosBundleId: 'com.routemate.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDYZ1XIomOuWFoCL-9v1YLf96-dw5jdgU',
    appId: '1:896053782358:ios:0d9458d20f533c815318f7',
    messagingSenderId: '896053782358',
    projectId: 'routemate-470316',
    storageBucket: 'routemate-470316.firebasestorage.app',
    iosClientId: '896053782358-abcdefghijklmnopqrstuvwxyz123456.apps.googleusercontent.com',
    iosBundleId: 'com.routemate.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDYZ1XIomOuWFoCL-9v1YLf96-dw5jdgU',
    appId: '1:896053782358:web:0d9458d20f533c815318f7',
    messagingSenderId: '896053782358',
    projectId: 'routemate-470316',
    authDomain: 'routemate-470316.firebaseapp.com',
    storageBucket: 'routemate-470316.firebasestorage.app',
  );
}
